name: Upload Release

on:
  release:
    types: [published]

jobs:
  upload-to-dropbox:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: release.yml
          workflow_conclusion: success
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Upload to Dropbox
        uses: aTable/deploy-to-dropbox@v1.0.7
        with:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          DROPBOX_DESTINATION_PATH_PREFIX: "/MCE Files/OMS/${{ github.event.release.name }}/"
          GLOB: "artifacts/*"
          DEBUG: false
